version: '2'
services:
  db:
    image: postgres:10
    environment:
      - "POSTGRES_USER=gopher"
      - "POSTGRES_PASSWORD=111"
      - "POSTGRES_DB=gopherland"
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
    ports:
      - "5775:5775/udp"
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
